Update user_profile_backend.js.yml

diff --git a/.github/workflows/user_profile_backend.js.yml b/.github/workflows/user_profile_backend.js.yml
--- a/.github/workflows/user_profile_backend.js.yml
+++ b/.github/workflows/user_profile_backend.js.yml
@@ -31,4 +31,16 @@ jobs:
         run: npm install mocha chai sinon --save-dev
           npm install --save-dev nyc
         working-directory: backend/user_profile_backend
-      - run: npm run test-with-coverage
+        
+      - name: Run Tests with Coverage
+        run: npm run test-with-coverage
+        continue-on-error: true
+
+      - name: Check Test Status and Prevent Merge
+        run: |
+          if [ ${{ job.status }} == "failure" ]; then
+            echo "Tests failed, preventing merge."
+            exit 1
+          else
+            echo "Tests passed, merge can proceed."
+          fi
